version: '3'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      - MYSQL_USR=${MYSQL_USR}
      - MYSQL_HOST=${MYSQL_HOST}
      - WP_DB_USR=${WP_DB_USR}
      - WP_DB_PSSWD=${WP_DB_PSSWD}
      - WP_DB_NAME=${WP_DB_NAME}
    depends_on:
      - mariadb
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      - MYSQL_USR=${MYSQL_USR}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception

volumes:
  mariadb-data:
    driver: local
  wordpress-data:
    driver: local

networks:
  inception:
    name: inception

