version: '3'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception

volumes:
  mariadb-data:
    driver: local
  wordpress-data:
    driver: local

networks:
  inception:
    name: inception

